ipam:
  mode: kubernetes
kubeProxyReplacement: false
l7Proxy: false
envoy:
  enabled: false
gatewayAPI:
  enabled: false
hubble:
  enabled: false
operator:
  replicas: 1
  resources:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {memory: 256Mi}
resources:
  requests: {cpu: 100m, memory: 256Mi}
  limits: {memory: 768Mi}
