target: all
multitenancy_enabled: false
ingest_storage:
  enabled: false
server:
  http_listen_port: 9009
  log_level: info
common:
  storage:
    backend: s3
    s3:
      endpoint: seaweedfs.storage.svc.cluster.local:8333
      region: us-east-1
      access_key_id: ${S3_ACCESS_KEY}
      secret_access_key: ${S3_SECRET_KEY}
      insecure: true
      bucket_lookup_type: path
blocks_storage:
  s3:
    bucket_name: mimir-blocks
  tsdb:
    dir: /data/tsdb
  bucket_store:
    sync_dir: /data/bucket-sync
ruler_storage:
  backend: filesystem
  filesystem:
    dir: /data/rules
ruler:
  rule_path: /data/rule-work
  ring:
    kvstore: {store: inmemory}
    instance_addr: 127.0.0.1
ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1
    instance_addr: 127.0.0.1
    tokens_file_path: /data/tokens
distributor:
  ring:
    kvstore:
      store: inmemory
    instance_addr: 127.0.0.1
compactor:
  data_dir: /data/compactor
  sharding_ring:
    kvstore:
      store: inmemory
    instance_addr: 127.0.0.1
store_gateway:
  sharding_ring:
    replication_factor: 1
    kvstore:
      store: inmemory
    instance_addr: 127.0.0.1
limits:
  compactor_blocks_retention_period: 24h
usage_stats:
  enabled: false
